# Generated by Django 4.2 on 2025-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
