# Generated by Django 4.2 on 2025-03-13 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revision', '0002_solved_delete_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='user',
            field=models.ForeignKey(default=3432, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
